CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Clientes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" text NOT NULL,
    "Email" text NOT NULL,
    "Telefone" text NOT NULL,
    "TipoDocumento" text NOT NULL,
    "Documento" text NOT NULL,
    "Senha" text NOT NULL,
    "UsuarioCriacao" text NOT NULL,
    "DataCriacao" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Clientes" PRIMARY KEY ("Id")
);

CREATE TABLE "Enderecos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdCliente" integer NOT NULL,
    "Tipo" text NOT NULL,
    "Logradouro" text NOT NULL,
    "Numero" text NOT NULL,
    "Complemento" text NOT NULL,
    "Bairro" text NOT NULL,
    "Cidade" text NOT NULL,
    "Uf" text NOT NULL,
    "UsuarioCriacao" text NOT NULL,
    "DataCriacao" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Enderecos" PRIMARY KEY ("Id")
);

CREATE TABLE "Logs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Entidade" text NOT NULL,
    "ValorAnterior" text NOT NULL,
    "ValorPosterior" text NOT NULL,
    "UsuarioCriacao" text NOT NULL,
    "DataCriacao" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Logs" PRIMARY KEY ("Id")
);

CREATE TABLE "Pedidos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdCliente" integer NOT NULL,
    "IdProduto" integer NOT NULL,
    "ValorTotal" numeric NOT NULL,
    "Desconto" numeric NOT NULL,
    "ValorFinal" numeric NOT NULL,
    "StatusEntrega" integer NOT NULL,
    "TipoPagamento" text NOT NULL,
    "NumeroParcelas" integer NOT NULL,
    "UsuarioCriacao" text NOT NULL,
    "DataCriacao" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Pedidos" PRIMARY KEY ("Id")
);

CREATE TABLE "Produtos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Titulo" text NOT NULL,
    "Descricao" text NOT NULL,
    "Valor" numeric NOT NULL,
    "Estoque" integer NOT NULL,
    "UsuarioCriacao" text NOT NULL,
    "DataCriacao" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Produtos" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260327233346_InitialCreate', '10.0.5');

COMMIT;
